名字: 制造TWRP装置

在:
  workflow_dispatch:
输入:
      IMG_URL:    
描述: 'IMG_URL'
所需: 真正的
默认的: ''

工作:
建筑:
如果: id = = github．event．repository．owner．id
    runs-on: ubuntu-20.04
    
步骤:
    - 名字: 退房
用途: actions/checkout@main
      
    - 名字: 营造环境
跑: |
sudo apt更新
sudo apt -y install python python3 python-pip python3-pip cpio wget
安装twrpdtgen
mkdir dt
      
    - 名字: 下载引导或恢复
跑: |
aria2c "${{ github.event.inputs.IMG_URL }}"
l š
      
    - 名字: 开始建造
跑: |
python3 -m twrpdtgen -o dt/ *.img
    - 名字: ZIP设备树
跑: |
zip -r DeviceTree.zip ./dt
    - 名字: 上载至发布
用途: softprops/action-gh-release@v1
与:
档案: |
          ./DeviceTree.zip
名字: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
身体: twrp设备
Ê v:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
